# Generated by Django 4.2.1 on 2023-05-31 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_product_image_of_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='expiry_date',
        ),
    ]
